import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import Services from "@/components/Services";
import Another from "@/components/Another";
import CarList from "@/components/CarList";
import Script from "next/script";
import Footer from "@/components/Footer";
export default function Home() {
  
  return (
    <>
      <Head>
        <title>Car Shop</title>
        <meta name="deScription" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
     
      </Head>
      <div>
        <Header />
        <Banner />
        <Services />
        <CarList />
        <Another />


        <Footer />
      </div>

      {/* <Script src="https://code.jquery.com/jquery-3.4.1.min.js" /> */}
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" />
      <Script src="lib/wow/wow.min.js" />
      <Script src="lib/easing/easing.min.js" />
      <Script src="lib/waypoints/waypoints.min.js" />
      <Script src="lib/counterup/counterup.min.js" />
      <Script src="lib/owlcarousel/owl.carousel.min.js" />
      <Script src="lib/tempusdominus/js/moment.min.js" />
      {/* <Script src="lib/tempusdominus/js/moment-timezone.min.js" /> */}
      <Script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js" />
    </>
  );
}
