import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import React from "react";

export default function bid() {
  return (
    <div>
      <Head>
        <title>Car Shop</title>
        <meta name="deScription" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow:wght@600;700&family=Ubuntu:wght@400;500&display=swap"
          rel="stylesheet"
        />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
          rel="stylesheet"
        />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
          rel="stylesheet"
        />

        <link href="lib/animate/animate.min.css" rel="stylesheet" />
        <link
          href="lib/owlcarousel/assets/owl.carousel.min.css"
          rel="stylesheet"
        />
        <link
          href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <div class="container mt-5 mb-5">
        <div class="row d-flex justify-content-center">
          <div class="col-md-10">
            <div class="">
              <div class="row">
                <div class="col-md-6 my-auto">
                  {/* <div class="images bg-dark"> */}{" "}
                  <img
                    id="main-image"
                    className="w-100 bg-cover"
                    src="https://img.freepik.com/free-photo/yellow-sport-car-with-black-autotuning-road_114579-5051.jpg?w=740&t=st=1680364469~exp=1680365069~hmac=7b8506b845b030ef94125ce1a7be04e728866b34d48de8af9c6125ba32193c3d"
                    width="400"
                  />
                </div>
                <div class="col-md-6">
                  <div class="card-body pb-0 px-4">
                    <div class="d-flex py-4 justify-content-between">
                      <h3>Toyota Corola</h3>
                    </div>

                  
                    {/* <hr class="my-0" /> */}
                    <div class="card-body">
                     
                      <div class="d-flex justify-content-between ">
                        <p className="">V8</p>
                        <p class="text-dark">Hybrid</p>
                        <p class="text-dark">4wheel</p>
                        <p class="text-dark">Dizeil</p>
                        <p class="text-dark">Dizeil</p>

                      </div>
                     
                    </div>
                    <div class="d-flex justify-content-between ">
                      <p className="">Last Bids</p>
                      <p class="text-dark">7000000FCFA </p>
                      <s className="text-danger">6500000FCFA</s>
                    </div>

                    
                   <p className="fw-bold">Place Bid</p>
                    

                    <div class="sizes"></div>
                    <div class="cart d-flex mt-1 align-items-center">
                      <input type="text" className="form-control "  placeholder="Enter Amount"/>
                      <button class="btn btn-danger text-uppercase mx-2 px-4">
                        Bid
                      </button>
                    
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
}
